### ISSUE TITLE
Activating suproject in nested project deletes keys

### ISSUE THREAD

**Issue by michalstolarczyk** [pepkit/peppy#250]
When a subproject just replaces one attribute of the project, like: 

```
subprojects:
  dog:
    metadata:
      sample_annotation: sample_annotation_sp1.csv
```

in 

```
metadata:
  sample_annotation: sample_annotation.csv
  output_dir: $HOME/hello_looper_results
  pipeline_interfaces: ../pipeline/pipeline_interface.yaml
```

the `output_dir` and `pipeline_interfaces` keys are lost. 
This is probably the result of our recent transition to `attmap`
