### ISSUE TITLE
Proposed config version update

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#334]
PEP config format version 2:

```
config_version: 2.0
sample_table: blahblahblah/blah.csv
subsample_table: blahblah/subsamples.csv
compare_table: .../compare.csv
sample_modifiers:
  constants:
    attribute1: value
    attr2: val2	
  implied:
    organism:
      human:
        imp_attr: value
      mouse:
        imp_arr: val2
  synonyms:
    oldattr: newattr
  derived: [read1, read2, other_attr]
  derived_sources:
    key1: "path/to/derived/value/{sample.attribute}/{project.attribute}"
    key2: "path/to/derived/value/{sample.attribute}/{project.attribute}"

subprojects:
  etc.

imports:
  - external_pep.yaml
  - http://url.com/pep.yaml

# project-specific attributes
# attributes specifically required by your project
genome: abcd

# tool-specific connections?
# settings read by other tools
divvy:
  divvy settings

looper:
  pipeline_config: ...
  pipeline_args: ...
  pipeline_interfaces: ...
  output_dir:...
  results_subdir: ...
  submission_subdir: ...
```

Related to: 
- https://github.com/pepkit/peppy/issues/169
- https://github.com/pepkit/peppy/issues/200
- https://github.com/pepkit/peppy/issues/222
- https://github.com/pepkit/peppy/issues/272
- https://github.com/pepkit/peppy/issues/299
- https://github.com/pepkit/peppy/issues/332
