### ISSUE TITLE
implement project_modifiers.imply

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/peppy#342]
Say peppy offered a `project_modifiers.imply`, which is exactly the sample as the `sample_modifiers` version but operates on a project. Then, I could do:

```yaml
name: global looper pipeline interfaces
pep_config: 2.0.0
project_modifiers:
  imply:
    if:
      pep_type: [ATAC, ATAC-seq, DNAse, blah, blah, blah]
    then:
       looper.pipeline_interfaces: [x.yaml, y.yaml, z.yaml]
```

_Originally posted by @nsheff in https://github.com/pepkit/looper/issues/244#issuecomment-611026530_

**Comment by nsheff** [comment]
One complexity: referring to things with `looper.pipeline_interfaces`, or implying structured attributes instead of just strings...

**Comment by nsheff** [comment]
another thought: if we go this route, do you think you'd want `amendments` and `imports` to fall under `project_modifiers` ? 

the it'd be:

```
project_modifiers:
  amend: ...
  imply: ...
  import: ...
sample_modifiers:
  append: ...
  imply: ...
  derive: ...
  ...
```
