### ISSUE TITLE
Project with no config

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/peppy#343]
`peppy.Project` object could be in theory created from a csv. No project config file needed. This would be even more approachable for individuals that just speak spreadsheet format.

**Comment by nsheff** [comment]
I think we should prioritize this; it will make it easier to adopt PEP for current use cases that lack a yaml.

**Comment by stolarczyk** [comment]
example CSV: https://github.com/nf-core/test-datasets/blob/rnaseq/samplesheet/v3.1/samplesheet_test.csv

**Comment by nsheff** [comment]
Just to add to this, I'd like to be able to do this:

```
eido convert https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/samplesheet/v3.1/samplesheet_test.csv -f yaml-samples
```

**Comment by stolarczyk** [comment]
you can do this. You should have gotten an error saying:

```
peppy.exceptions.InvalidSampleTableFileException: sample_table is missing 'sample_name' column; you must specify sample_names in sample_table or derive them
```

Therefore, you need to adjust sample table index column name to match the metadata. They used "sample", so:

```
~ eido convert https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/samplesheet/v3.1/samplesheet_test.csv -f yaml-samples --st-index sample 

Found 2 samples with non-unique names: {'WT_REP1', 'RAP1_UNINDUCED_REP2'}. Attempting to auto-merge.
Running plugin yaml-samples
- fastq_1: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357072_1.fastq.gz
  fastq_2: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357072_2.fastq.gz
  sample: WT_REP2
  strandedness: reverse
  
- fastq_1: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357073_1.fastq.gz
  sample: RAP1_UNINDUCED_REP1
  strandedness: reverse
  
- fastq_1: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357076_1.fastq.gz
  fastq_2: https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357076_2.fastq.gz
  sample: RAP1_IAA_30M_REP1
  strandedness: reverse
  
- fastq_1:
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357070_1.fastq.gz
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357071_1.fastq.gz
  fastq_2:
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357070_2.fastq.gz
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357071_2.fastq.gz
  sample: WT_REP1
  strandedness: reverse
  
- fastq_1:
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357074_1.fastq.gz
  - https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357075_1.fastq.gz
  sample: RAP1_UNINDUCED_REP2
  strandedness: reverse
```
