### ISSUE TITLE
move amendments and imports under project_modifiers

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/peppy#344]
`amendments` and `imports` to fall under `project_modifiers` ? 

the it'd be:

```
project_modifiers:
  amend: ...
  imply: ...
  import: ...
sample_modifiers:
  append: ...
  imply: ...
  derive: ...
  ...
```

_Originally posted by @nsheff in https://github.com/pepkit/peppy/issues/342#issuecomment-611050195_
