### ISSUE TITLE
Can you use project-level attributes in derived attributes?

### ISSUE THREAD

**Issue by nsheff** [pepkit/peppy#345]
can you use project-level attributes in derived attributes? 

```
  derive:
    attributes: [read1, read2, other_attr]
    sources:
      key1: "path/to/derived/value/{sample.attribute}/{project.attribute}"
      key2: "path/to/derived/value/{sample.attribute}/{project.attribute}"
```

or is it no namespaces allowed, always assumed to be a sample attribute?

```
  derive:
    attributes: [read1, read2, other_attr]
    sources:
      key1: "path/to/derived/value/{sample_attribute}"
      key2: "path/to/derived/value/{sample_attribute}"
```
