### ISSUE TITLE
Referencing python package files as paths in PEP

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/peppy#350]
I propose a new type of string substitution in a PEP that is capable of referencing files existing inside a Python package.

Take for example a PEP produced with `geofetch`. This is a package that has both a pipeline and interfaces for it. But (correct me if I'm wrong) in order for looper to use the amendment adding the interface, the user would need to additionally, clone the repository and either change the PEP manually to point to their newly cloned interface file, or set up the `CODE` environment variable:
```yaml
...
project_modifiers:
  amend:
    sra_convert:
      looper:
        results_subdir: sra_convert_results
      sample_modifiers:
        append:
          SRR_files: SRA
          pipeline_interfaces: ${CODE}/geofetch/pipeline_interface_convert.yaml
...
```
The thing is, if the interface file is distributed with the pipeline, it would be great to do something like this to reference it (nomenclature/syntax to be discussed):
```yaml
...
          pipeline_interfaces: {pypi:geofetch/pipeline_interface_convert.yaml}
...
```
The only thing the `geofetch` package has to change is add `pipeline_interfec_convert.yaml` to the `Manifest.in`.
Now pipeline packages are pip installable and the user doesn't have to either change the PEP or point 

Internally, this seems straightforward to implement too:
```python
import pkg_resources
pkg_resources.resource_filename("geofetch", 'pipeline_interface_convert.yaml')
```
