### ISSUE TITLE
`ComposeError` thrown loading PEP

### ISSUE THREAD

**Issue by NLeRoy917** [pepkit/peppy#373]
Attempting to load the following PEP [config file](https://github.com/pepkit/data.pephub/blob/master/demo/node_alias/project_config.yaml) throws an uncaught `ComposeError` from peppy. Stack trace:

```
yaml.composer.ComposerError: found undefined alias 'baz'
  in "<my_path_to_config_file>", line 10, column 8
```

These are the contents of the configuration file:
```yaml
pep_version: "2.0.0"
sample_table: sample_table.csv
output_dir: $HOME/hello_looper_results
pipeline_dir: $HOME/pipeline_dir

project_modifiers:
  import:
    - project_config1.yaml

timer: *baz
```

I can catch this error on my end, but seeing as it's being thrown from within Peppy, I thought I'd open an issue here.
