### ISSUE TITLE
Allow null subsample tables in `peppy.Project`

### ISSUE THREAD

**Issue by nleroy917** [pepkit/peppy#393]
I was attempting to create a new `peppy.Project` object with the following config:

```yaml
name: GSE96155
pep_version: 2.1.0
sample_table: GSE96155_annotation.csv
subsample_table: null
...
```
And `peppy` threw the following error: `TypeError: Provided argument has to be a List[str] or a str, got 'NoneType'`

Based on the discussion over at `geofetch`: https://github.com/pepkit/geofetch/issues/80, `peppy` should allow null sub sample tables.
