### ISSUE TITLE
Pandas frame.append method is deprecated

### ISSUE THREAD

**Issue by matinnuhamunada** [pepkit/peppy#416]
Hi, thanks for the nice tool here :)

When running `peppy.Project(project_config_file)`, I keep getting this warning:
```bash
/home/matinnu/miniconda3/envs/snakemake/lib/python3.10/site-packages/peppy/project.py:103: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(ser, ignore_index=True)
```

This is how the config file looks like:
```yaml
name: example2
pep_version: 2.0.0
description: "test_project"
sample_table: samples.csv
prokka-db: prokka-db.csv
gtdb-tax: gtdbtk.bac120.summary.tsv
output_dir: "$HOME/test"
```

This does not throw an error, but might be something to be addressed in the long run?
