### ISSUE TITLE
Env variables in config file are not expanding

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/peppy#464]
Looking at [pep-pipelines](https://github.com/pepkit/pep-pipelines) for snakemake integration:

https://github.com/pepkit/pep-pipelines/blob/805cbc75ca2dfdf57bfee412987816e5f7c52d0a/pipelines/pep-snakemake/simple/examples/wc_config.yaml#L1-L11

```
name: snakemake-line-count

pep_version: 2.0.0
sample_table: wc_sample_table.csv
output_dir: $HOME/pep-snakemake/simple/examples

sample_modifiers:
  derive:
    attributes: [filename]
    sources:
      F: $CODE/pep-snakemake/simple/examples/{sample_name}.txt
```

The environment variables are not being expanded. I confirmed that, if I add the absolute path manually, the pipeline works fine.

Using `peppy v0.40.0a5`
