### ISSUE TITLE
Should appending sample modifiers override column values in sample.csv?

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/peppy#481]
I noticed that appending a value via sample modifiers in the project config will not override a column value if it already exists in the sample.csv table, e.g.

```
name: looper_advanced_test
pep_version: 2.0.0
sample_table: annotation_sheet.csv
sample_modifiers:
  append:
    toggle: 0
```

```
sample_name,protocol,data_source,SRR,Sample_geo_accession,read1,read2,toggle
sample1,PROTO1,SRA,SRR5210416,GSM2471255,SRA_1,SRA_2,1
sample2,PROTO1,SRA,SRR5210450,GSM2471300,SRA_1,SRA_2,1
sample3,PROTO2,SRA,SRR5210398,GSM2471249,SRA_1,SRA_2,1
```

toggle will still be set to `1` for all the samples.

**Should it override? Or should we at least warn the user that this sample modifier is being ignored?**
